### ISSUE TITLE
Missing name in Game Over screen

### ISSUE THREAD

**Issue by TimJones** [halfers1986/text-adventure#1]
When failing in my quest (I went back to bed) I got the following text in the Game Over screen:
```
Nobody will ever remember your name, #firstNamelastName#, nor will songs be sung of your deeds.
```
I guess `#firstNamelastName#` should be substituted with the playre name :)

**Comment by halfers1986** [comment]
Actually it was just supposed to be a joke... 'cause "nobody will remember your name"...

**Comment by TimJones** [comment]
Damn, you should be a writer or something, that shit's genius!!
